language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t sqweghen/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true sqweghen/react-test npm run test

after_success:
  - docker build -t sqweghen/multi-client ./client
  - docker build -t sqweghen/multi-nginx ./nginx
  - docker build -t sqweghen/multi-server ./server
  - docker build -t sqweghen/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take the images and push them to docker hub
  - docker push sqweghen/multi-client
  - docker push sqweghen/multi-nginx
  - docker push sqweghen/multi-server
  - docker push sqweghen/multi-worker